-- TROPA DA LAN WEB
-- Execute este arquivo no Supabase > SQL Editor.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room text not null check (char_length(room) between 1 and 50),
  username text not null check (char_length(username) between 2 and 24),
  content text not null check (char_length(content) between 1 and 1000),
  client_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_room_created_at_idx
  on public.messages (room, created_at desc);

alter table public.messages enable row level security;

-- MVP público: qualquer visitante com a Publishable Key pode ler e enviar mensagens.
-- Para um projeto público maior, troque por autenticação e regras por usuário.
drop policy if exists "Tropa public read messages" on public.messages;
create policy "Tropa public read messages"
  on public.messages for select
  to anon, authenticated
  using (true);

drop policy if exists "Tropa public insert messages" on public.messages;
create policy "Tropa public insert messages"
  on public.messages for insert
  to anon, authenticated
  with check (
    char_length(username) between 2 and 24
    and char_length(content) between 1 and 1000
    and char_length(room) between 1 and 50
  );

-- Ativa eventos INSERT da tabela no Supabase Realtime.
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;
